language: go
go:
    - 1.1
    - 1.2
    - tip
install:
    - go get github.com/go-sql-driver/mysql
    - go get code.google.com/p/gcfg
    - go get github.com/bradfitz/gomemcache/memcache
    - go get github.com/braintree/manners
    - go get github.com/dustin/randbo
    - go get github.com/go-sql-driver/mysql
    - go get github.com/lestrrat/go-server-starter-listener
    - go get github.com/lestrrat/go-test-mysqld
    - go get github.com/vmihailenco/msgpack
script:
    - STF_DEBUG=1:`pwd`/test.log go test -v . || cat `pwd`/test.log