language: go
go:
    - 1.1
    - 1.2
    - tip
install:
    - sh build.sh
script:
    - SKIP_BUILD=1 sh test.sh || (cat `pwd`/test.log && exit 1)
after_success:
    - go get github.com/mattn/goveralls
    - go get github.com/axw/gocov/gocov
    - go get code.google.com/p/go.tools/cmd/cover
    - export PATH="$HOME/gopath/bin:$PATH"
    - goveralls $COVERALLS_TOKEN
env:
    global:
        secure: "fhKD8yvdUoK5JJhSe4wte+spwUIg8C6VQqpYh31thL9DyfeuYvGC6JwWlEkm92XKTrKe+uJYICh5TlJSI+t3VNNwPV8CsQp+qlzn1MWjnfz9lj7/gfN62Hd4j9cQKeHlDQi2MdfGR0Eq3LcyB4yvZoLGtvoN18W9SQUSp7xJDvM="
    matrix:
        - STF_QUEUE_TYPE=redis
