language: go
go:
    - 1.1
    - 1.2
    - tip
install:
    - go get github.com/go-sql-driver/mysql
    - go get code.google.com/p/gcfg
    - go get github.com/bradfitz/gomemcache/memcache
    - go get github.com/braintree/manners
    - go get github.com/dustin/randbo
    - go get github.com/go-sql-driver/mysql
    - go get github.com/lestrrat/go-apache-logformat
    - go get github.com/lestrrat/go-file-rotatelogs
    - go get github.com/lestrrat/go-server-starter-listener
    - go get github.com/lestrrat/go-test-mysqld
    - go get github.com/vmihailenco/msgpack
script:
    - STF_DEBUG=1:`pwd`/test.log go test -tags q4m -v . || (cat `pwd`/test.log && exit 1)
after_success:
    - go get github.com/mattn/goveralls
    - go get github.com/axw/gocov/gocov
    - go get code.google.com/p/go.tools/cmd/cover
    - export PATH="$HOME/gopath/bin:$PATH"
    - goveralls $COVERALLS_TOKEN
env:
    global:
        secure: "fhKD8yvdUoK5JJhSe4wte+spwUIg8C6VQqpYh31thL9DyfeuYvGC6JwWlEkm92XKTrKe+uJYICh5TlJSI+t3VNNwPV8CsQp+qlzn1MWjnfz9lj7/gfN62Hd4j9cQKeHlDQi2MdfGR0Eq3LcyB4yvZoLGtvoN18W9SQUSp7xJDvM="
