storage1: ../bin/storage --listen :9001 --root=storage1
storage2: ../bin/storage --listen :9002 --root=storage2
storage3: ../bin/storage --listen :9003 --root=storage3
dispatcher1: ../bin/dispatcher --config ../etc/config.gcfg
